# Generated by Django 3.0.7 on 2020-06-16 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0106_role_default_color"),
        ("axians_netbox_pdu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDUStatus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("power_usage", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.OneToOneField(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="dcim.Device"
                    ),
                ),
            ],
        ),
    ]
